### ISSUE TITLE
Purpose of the lastValue transformer

### ISSUE THREAD

**Issue by tgriesser** [transduce/transduce#16]
It seems like `lastValue` is a no-op in its uses in the current codebase. It's always called with no `init` value and therefore won't work in the `asCallback` and `asyncCallback` as the `stepper.init()` will be undefined a few lines down.

Wondering just because I wanted to change the signatures of those to take an initializing value, but as I was looking I didn't really see how omitting the transformer could possibly work as-is.

**Comment by kevinbeaty** [comment]
It truly does just maintain the last value sent through the transformer, i.e. there is no need for aggregating results.   `init` is `undefined` because at that point, there is no value sent.  The `step` method always returns the second argument `item` which becomes the new `result`.  If you need the behavior of `lastValue` but want a different `init` you can use `lastValue(default)` as the optional `xf` arg.

The [underscore-transducer](http://simplectic.com/projects/underscore-transducer/) and [underarm](http://simplectic.com/projects/underarm/) demos use `asCallback` with `tap` to transform browser events.  `transduce-stream` used to use it, but I recently remove the dependency on `transduce` and implemented more directly. 

Does that make sense?

**Comment by kevinbeaty** [comment]
It could be useful to call `transformer(xf)` on `xf` (similar to `into`) if supplied to allow doing something like `asCallback(t, [])` to buffer results into an array.

**Comment by tgriesser** [comment]
> Does that make sense?

Not exactly. I guess I don't understand how [these lines](https://github.com/transduce/transduce/blob/383b78bb8c45b44594098e6f7bb5a4011068dc98/push/asCallback.js#L22-L24) are ever supposed to be used for anything.

**Comment by kevinbeaty** [comment]
All it's doing is creating a transformer if one is not provided. The transformer (either provided or default) is used to initialize the transducer, just like `transduce`.

I use the `lastValue` transformer a couple cases:
- I'm not interested in aggregating results and am only interested processing the transformed items incrementally.  In this case you could use `tap` or `forEach` etc. to tap into the transformation. This is what the linked demos are doing.
- I'm only expecting a single value (`find`, `some`, `any`, etc.) and just want that value instead of dumping into an array or other data structure.

Arguably, it is the wrong default transformer (or there should be no default)...  I am definitely open to something that makes more sense.  What were you expecting/hoping?

**Comment by kevinbeaty** [comment]
@tgriesser I changed `asCallback` and `asyncCallback` functions to accept an `init` argument similar to `into` as part of #20 .   This allows you to do something like `asCallback(t, [])`, `asCallback(t, {foo:bar})`, etc.

 If `undefined` maintains previous behavior as `transformer` returns `lastValue` if passed `undefined`.

Does this help?  Can I close this issue?

**Comment by kevinbeaty** [comment]
Version 0.6.0
