### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by tgriesser** [transduce/transduce#53]
When I said that I was going to ask about splitting async out into another package, I couldn't quite describe why I thought this should be the case.

In redoing the `into` implementation, I think I've realized - Promises are a bad/heavyweight abstraction for dealing with transducers internally.

I think the ideal async implementation would really just be about providing a push implementation of a transducer, perhaps some sugar for events / streams, and perhaps something simple for consuming a promise value (duck type checking for `.then` / `.catch`) but the need for a full on `Promise` dependency seems overkill.

**Comment by kevinbeaty** [comment]
Well, my opinions seem to differ from yours on Promises, but I do concede that the `async` package is the most experimental part of this library, so it probably makes sense to split it out, especially if that means you'll stop bugging me about it (kidding).

Will you at least let me keep the `_internal` package so I can reuse `intoImpl`, etc?  It does not have to be exported, I can require `transduce/lib/_internal` (or perhaps `require('transduce/_internal')` or some other name).  Perhaps we should remove the `ArrayIterable`, etc. from the public API as well and require `_internal` for experimental/undocumented features.

I wonder if we should make a goal of `transduce` to act as a base to build other transducer libraries (e.g. `duce`, `underarm`, `transduce-async`) and include functionality with that in mind.  That is how this library started, and much of it will come naturally... Just a thought.

Do you think we should also split out `string`, `array` and `math`?  Or do you think those belong here?

**Comment by tgriesser** [comment]
I'm not necessarily saying we **need** to split it out yet - just that it might be good to see if we can discuss use cases and see if we can pair it down a bit so the implementation is more of a primitive which acts on promises rather than depend on them internally as much as they do now.

Promises are very coarse - they're an all or nothing guarantee of a set resolving, whereas transducers feel more suited as a stream of individual bits of data. You sort of lose a lot of the benefit of transducers when coercing everything to a promise every step of the way. Could a duck type on `.then` serve a lot of the same purpose?

I'm not as concerned about the external dependency as the implementation.

**Comment by kevinbeaty** [comment]
Sure, happy to discuss and reduce the primitives, if possible.

Fun trivia: My initial interest in transducers stem from this async package.  The fact you could define the transformations in asynchronous contexts was more interesting than any other feature, to me.  The [demo page](http://simplectic.com/projects/underarm/) for underarm (formerly known as underscore-transducer) was my first foray into transducers after watching the Clojure video. You can check out some of the examples on that page to understand some of what I was thinking with the async methods here.  Soon after my initial implementation, transducers-js and the "transformer protocol" version of transducers.js came out, so I rewrote everything to be based on those libraries (using what is now any-transduce) and added things like async as extensions.  Eventually, I realized I was very close to writing my own implementation of transducers, and this library was born.  So it was really an accident we ended up here.

I digress mostly to set the context of what I was originally thinking.  Rich Hickey mentioned in passing that many "Reactive" frameworks could be rewritten using transducers, and thus my interest was born.  The promise implementation was inspired by an "End of Reactive" talk by Erik Meijer and it's hopefully in the same spirit of what was discussed there.

Please note that Promises are only used in async, and if you don't use that functionality, nothing needs to be installed.  Everything in other packages work just as well with any other library that use transducers from other libraries.

All that said, I have spent much more time recently refining the non-async stuff, so the async stuff could probably use some love.

I think of Promises as asynchronous primitive, epecially since they are now part of ES6.  Why do you consider depending on the ES6 Promise API "heavyweight"?

**Comment by tgriesser** [comment]
> I think of Promises as asynchronous primitive, especially since they are now part of ES6. 

I think they're one option of an async primitive, one which is best suited for providing a contract for an single eventual value. The Observable interface in combination with transducers might be worth exploring, gives a bit more fine grained control over the async value. 

> Why do you consider depending on the ES6 Promise API "heavyweight"?

It's the fact that Promises A+ make a guarantee of executing in the next tick of the event loop - regardless of whether the value is a primitive or something that does not otherwise require that guarantee. So when you use that as the primitive, it ends up being something like setting an unnecessary `setTimeout` all over the place.

Also good related reading on some of what you lose with promises: https://twitter.com/mattpodwysocki/status/583332498844696576

(Note: I love promises, I just am questioning whether they're the right primitive here)

>  The promise implementation was inspired by an "End of Reactive" talk by Erik Meijer and it's hopefully in the same spirit of what was discussed there.

Funny, reading some Erik Meijer stuff is what made me think about the async stuff a bit more as well :)

> All that said, I have spent much more time recently refining the non-async stuff, so the async stuff could probably use some love.

No rush - I haven't started using the async stuff in practice yet (working on patterns to build up the sql queries in knex consistently) but I will be soon (accumulating values off of query streams piped through transducers) so maybe once I get there I'll have more real-world opinions :)

I definitely want good async for the same reasons you do - I'm just wondering whether the promise should be internally responsible for the resolution of async values (`Promise.all`) or whether it should just provide various interfaces for seamless interop. with different patterns.

**Comment by kevinbeaty** [comment]
Another thing I found interesting that could be relevant is Kris Kowal's [General Theory of Reativity](https://github.com/kriskowal/gtor).   Also plenty of interesting stuff in the FP world.

**Comment by kevinbeaty** [comment]
I'm thinking about this again, and am considering moving the async package, transduce-gen and any-transduce outside of the transduce organization (into github.com/kevinbeaty) and leaving only transduce and transduce-stream here.  This would allow us to focus on a core API in transduce and experimentation can be performed externally (in "duce" and whatever async/gen becomes).

The async stuff here is currently just a grab bag of (mostly) half-baked experimental features. We can reintroduce async features as they make sense. Thoughts?

**Comment by tgriesser** [comment]
Maybe vanilla push transducers could be kept around though?

**Comment by kevinbeaty** [comment]
Do you mean `async.callback` or something more/different?

**Comment by kevinbeaty** [comment]
@tgriesser I would like to remove the `any-promise` dependency from `transduce` due to issues described in kevinbeaty/any-promise#1

OK to merge #55 or should I update the PR to only remove the `async` functions that rely on `any-promise`?

**Comment by tgriesser** [comment]
Either of those sound good
